// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATnTvLUjp3CRwg1LFV-p0h0F3xpo1YWbU',
    appId: '1:3175907362:web:6d0752a68102682c830a7b',
    messagingSenderId: '3175907362',
    projectId: 'parkinglotapp-34467',
    authDomain: 'parkinglotapp-34467.firebaseapp.com',
    storageBucket: 'parkinglotapp-34467.firebasestorage.app',
    measurementId: 'G-4434P85JDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0MSt2RXPwKZCh8jKbSu91_GP4coDJpok',
    appId: '1:3175907362:android:746d36f3d59b9dc9830a7b',
    messagingSenderId: '3175907362',
    projectId: 'parkinglotapp-34467',
    storageBucket: 'parkinglotapp-34467.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxyf3JE5XLZC81MaEG0JRVYLKPUR8Uycg',
    appId: '1:3175907362:ios:c2c8ca01865b7a14830a7b',
    messagingSenderId: '3175907362',
    projectId: 'parkinglotapp-34467',
    storageBucket: 'parkinglotapp-34467.firebasestorage.app',
    iosBundleId: 'com.example.parkingLotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxyf3JE5XLZC81MaEG0JRVYLKPUR8Uycg',
    appId: '1:3175907362:ios:c2c8ca01865b7a14830a7b',
    messagingSenderId: '3175907362',
    projectId: 'parkinglotapp-34467',
    storageBucket: 'parkinglotapp-34467.firebasestorage.app',
    iosBundleId: 'com.example.parkingLotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATnTvLUjp3CRwg1LFV-p0h0F3xpo1YWbU',
    appId: '1:3175907362:web:06460fc91b75a0d3830a7b',
    messagingSenderId: '3175907362',
    projectId: 'parkinglotapp-34467',
    authDomain: 'parkinglotapp-34467.firebaseapp.com',
    storageBucket: 'parkinglotapp-34467.firebasestorage.app',
    measurementId: 'G-C73STWPGZ0',
  );
}
